Animation Manager
BearlyHumans/squirrelville pull request #68
Opened 2021-09-16 10:07 UTC by coolasjake

- Added a data structure in the squirrel controller which uses a list of 'events' to expose animation options in the inspector.
- Added test animation events in the code (moving, idle, jump).

Test:
* Add an event to the Animation Events list in the Squirrel controller.
* Set the trigger to Jump / Moving / Not Moving.
* Set the type and param name to match an animation parameter in the animation controller (e.g. MoveState, int).
* Set the value to the expected value for the event chosen (0 = walk, 1 = move, 2 = jump).
* Play scene, player should be animating.

Bugs/Notes:
> Events are not set up in prefab/scene to avoid conflicts.
> Most events are not triggered in code yet.

2021-09-16 10:12 UTC, coolasjake commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix camera clipping into terrain + smoothing](https://trello.com/c/FLMi77ti/147-fix-camera-clipping-into-terrain-smoothing)

2021-09-18 05:24 UTC, 102747419 requested changes

2021-09-18 05:24 UTC, 102747419 commented on Capstone-Game/Assets/Editor/SquirrelControllerEditor.cs
> +}
Please delete this file as it is unused.

2021-09-18 05:50 UTC, 102747419 approved these changes

2021-09-18 05:50 UTC, merged